version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - app-tier

  myapp:
    image: fredyjimenezrendon/spring-data-reactive-redis
    command: [
        "-Dspring.redis.host=redis"
    ]
    ports:
      - '8080:8080'
    networks:
      - app-tier
