version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#    networks:
#      - app-tier
    ports:
      - '6379:6379'

  myapp:
    image: 'fredyjimenezrendon/spring-data-reactive-redis'
    ports:
      - '8080:8080'
#    networks:
#      - app-tie
